"""Add Unit table for lot-size 1 dispatching

Revision ID: 006
Revises: dcb434f47f7d
Create Date: 2026-04-16 17:22:54.504559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = 'dcb434f47f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('unit_no', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('prod_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prod_results_unit_id'), ['unit_id'], unique=False)
        batch_op.create_foreign_key('fk_prod_results_unit_id_units', 'units', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prod_results_unit_id_units', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prod_results_unit_id'))
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_work_order_id'))

    op.drop_table('units')
    # ### end Alembic commands ###
